/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kartu.tik;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author GeolseuDei
 */
public class UbahProfil extends javax.swing.JFrame {

    /**
     * Creates new form UbahProfil
     */
    public UbahProfil() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {

        }
        initComponents();
        setResizable(false);
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;
        setLocation(dx, dy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnGantiNama = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUbahPassword = new javax.swing.JButton();
        txtPasswordLama = new javax.swing.JPasswordField();
        txtPasswordBaru = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Nama :");

        btnGantiNama.setText("Ganti Nama!");
        btnGantiNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGantiNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGantiNama)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnGantiNama)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Profil", jPanel1);

        jLabel2.setText("Password lama :");

        jLabel3.setText("Password Baru :");

        jLabel4.setText("Ulangi Password Baru :");

        btnUbahPassword.setText("Ubah Password");
        btnUbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPasswordActionPerformed(evt);
            }
        });

        txtPasswordLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLamaActionPerformed(evt);
            }
        });

        txtPasswordBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordBaruActionPerformed(evt);
            }
        });

        txtRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUbahPassword)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtPasswordBaru)
                            .addComponent(txtPasswordLama))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUbahPassword)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Password", jPanel2);

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGantiNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGantiNamaActionPerformed
        KartuTIK k = new KartuTIK();
        if (!txtNama.getText().equalsIgnoreCase("")) {
            int leng = txtNama.getText().length();
            if (leng <= 21) {
                int val = JOptionPane.showConfirmDialog(this, "Apa anda yakin akan mengganti nama menjadi " + txtNama.getText() + " ?", "Peringatan!", JOptionPane.YES_NO_OPTION);
                if (val == JOptionPane.YES_OPTION) {
                    if (k.GantiNama(txtNama.getText(), k.idUser)) {
                        JOptionPane.showMessageDialog(this, "Ganti nama sukses!");
                        k.namaUser = txtNama.getText();
                        txtNama.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Ganti nama gagal.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nama tidak dapat di ganti lebih dari 20 huruf");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Masukkan nama!");
        }
    }//GEN-LAST:event_btnGantiNamaActionPerformed

    private void btnUbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPasswordActionPerformed
        KartuTIK k = new KartuTIK();
        String passwordlama, passwordbaru, repasswordbaru;
        if (!txtPasswordLama.getText().equalsIgnoreCase("")) {
            passwordlama = txtPasswordLama.getText();
            if (!txtPasswordBaru.getText().equalsIgnoreCase("")) {
                passwordbaru = txtPasswordBaru.getText();
                int leng = passwordbaru.length();
                if (leng > 4) {
                    if (!txtRePassword.getText().equalsIgnoreCase("")) {
                        repasswordbaru = txtRePassword.getText();
                        if (repasswordbaru.equals(passwordbaru)) {
                            if (k.PasswordLamaSama(passwordlama, k.idUser)) {
                                if (!passwordbaru.equals(passwordlama)) {
                                    int val = JOptionPane.showConfirmDialog(this, "Apa anda yakin akan mengubah password anda?", "Peringatan", JOptionPane.YES_NO_OPTION);
                                    if (val == JOptionPane.YES_OPTION) {
                                        if (k.GantiPassword(passwordbaru, k.idUser)) {
                                            JOptionPane.showMessageDialog(this, "Password berhasil diubah!");
                                            txtPasswordLama.setText("");
                                            txtPasswordBaru.setText("");
                                            txtRePassword.setText("");
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Password gagal diubah");
                                        }
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Password baru tidak boleh sama dengan password lama!");
                                    txtPasswordBaru.setText("");
                                    txtRePassword.setText("");
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Password lama tidak sama!");
                                txtPasswordLama.setText("");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Password baru tidak sama!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Masukkan ulang password baru anda!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password harus lebih dari 4 huruf!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Masukkan password baru!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Masukkan Password lama!");
        }
    }//GEN-LAST:event_btnUbahPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        KartuTIK k = new KartuTIK();
        if (k.tipeUser.equalsIgnoreCase("1")) {
            MenuAdmin m = new MenuAdmin();
            m.setVisible(true);
            this.dispose();
        } else {
            MenuMember m = new MenuMember();
            m.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPasswordLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLamaActionPerformed
        btnUbahPasswordActionPerformed(evt);
    }//GEN-LAST:event_txtPasswordLamaActionPerformed

    private void txtPasswordBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordBaruActionPerformed
        btnUbahPasswordActionPerformed(evt);
    }//GEN-LAST:event_txtPasswordBaruActionPerformed

    private void txtRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePasswordActionPerformed
        btnUbahPasswordActionPerformed(evt);
    }//GEN-LAST:event_txtRePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbahProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbahProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbahProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbahProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbahProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGantiNama;
    private javax.swing.JButton btnUbahPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPasswordBaru;
    private javax.swing.JPasswordField txtPasswordLama;
    private javax.swing.JPasswordField txtRePassword;
    // End of variables declaration//GEN-END:variables
}
